# Generated by Django 4.2.9 on 2024-02-03 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chefprofile', '0002_alter_chefprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
