# Generated by Django 4.2.9 on 2024-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefprofile', '0004_chefprofile_facebook_url_chefprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='tiktok_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
