# Generated by Django 4.2.10 on 2024-02-11 15:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefprofile', '0005_chefprofile_tiktok_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='profile_pic'),
        ),
    ]
