# Generated by Django 4.2.10 on 2024-02-13 17:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefprofile', '0006_alter_chefprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
