# Generated by Django 4.2.10 on 2024-02-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='deleteme', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
