# Generated by Django 4.2.10 on 2024-02-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_category_options_alter_post_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='blog.post'),
        ),
    ]
